[package]
name = "lscpu"
version = "1.0.7"
edition = "2024"
license = "GPL-3.0"
description = "Implementation of lscpu in rust"
repository = "https://github.com/mateolafalce/lscpu"
authors = ["Mateo Lafalce <mateolafalce@protonmail.com>"]

[dependencies]
paste = "1.0.15"

